### ISSUE TITLE
Attempting to edit the configuration of an existing DMP hub generates error.

### ISSUE THREAD

**Issue by HaydnEstate** [amattas/hass-dmp#12]
"Error: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"
![Screenshot 2023-08-31 1 47 24 PM](https://github.com/amattas/hass-dmp/assets/99776616/f144fdd2-8c1a-4694-af3c-76d832260287)
![Screenshot 2023-08-31 11 47 37 AM](https://github.com/amattas/hass-dmp/assets/99776616/15133116-5415-4d2e-ba31-4b2128a4ffd4)

**Comment by NebulaGazer** [comment]
Remove the word "await" from this line
https://github.com/amattas/hass-dmp/blob/141ee6c682245eff459471fd6efc204e867de7b7/custom_components/dmp/config_flow.py#L178

**Comment by HaydnEstate** [comment]
> Remove the word "await" from this line
> 
> https://github.com/amattas/hass-dmp/blob/141ee6c682245eff459471fd6efc204e867de7b7/custom_components/dmp/config_flow.py#L178

Thank you! That looks like it fixed it.
