### ISSUE TITLE
Bypass Switch Not Retaining Status

### ISSUE THREAD

**Issue by amattas** [amattas/hass-dmp#16]
When using the bypass switch to bypass a zone, the switch resets to false even when the zone is bypassed.

**Comment by NebulaGazer** [comment]
Few questions:

- Is the status sensor reporting correctly? 
- Is the zone actually bypassed? If you arm from the keypad I believe it warns you about bypassed zones.
- If you enable debug logging and hit the refresh status button, what is reported there?  Do the zones being updated match what your zone configuration is? 
- Does a manual bypass from the keypad report on the switch or sensor?
- Does arm/disarm work properly?

**Comment by amattas** [comment]
I suspect this may actually be a configuration problem as I’m thinking about it. I made some network changes the same day I updated to the latest version. Will provide an update tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amattas** [comment]
Yup, this was all me - forgot to update both IP addresses.
